#include "GPIO.h"

void GPIO (void){
		//gpioc 13 out put

	RCC->APB2ENR |= RCC_APB2ENR_IOPBEN;
	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;

	GPIOC->BSRR |= GPIO_BSRR_BS13 ;
	GPIOC->CRH &= ~GPIO_CRH_CNF13;//general purpose output push-pull
	GPIOC->CRH &= ~GPIO_CRH_MODE13;
	
	GPIOB->CRH &= ~GPIO_CRH_MODE10;
	GPIOB->CRH |= GPIO_CRH_MODE10;
	GPIOB->CRH &= ~GPIO_CRH_CNF10;
	GPIOB->CRH |= GPIO_CRH_CNF10;//I2C clock
	
	GPIOB->CRH &= ~GPIO_CRH_MODE11;
	GPIOB->CRH |= GPIO_CRH_MODE11;
	GPIOB->CRH &= ~GPIO_CRH_CNF11;
	GPIOB->CRH |= GPIO_CRH_CNF11;//I2C Data I/O

}

